source "https://rubygems.org"
gem 'capistrano-puppet'
gem 'capistrano-ext-rvm'
gem 'capistrano-ext-rvm-bundler'
gem 'rvm-capistrano'
gem 'facter'
gem 'puppet'
gem 'hiera'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'bundler'
gem 'rvm'
gem 'capistrano', github: 'capistrano/capistrano', branch: 'v3'
